helloworld:
    path: /hello/world
    controller: App\Controller\HelloWorldController::hello
today:
    path: /today/date
    controller: App\Controller\TodaysDateController::today
random:
    path: /random/number
    controller: App\Controller\RandomNumberController::random
